#!/bin/sh

cd "$(dirname "$0")"

#echo "Enter Certificate Domain:"
#read domain

openssl genrsa -out server.key 1024
openssl req -sha256 -key server.key -new -out server.csr -config openssl.cnf
openssl req -sha256 -key server.key -new -out server.pem -config openssl.cnf -x509 -days 365

openssl rsa -inform pem -in server.key -outform der -out Web/server.key
openssl x509 -inform pem -in server.pem -outform der -out Web/server.der
#openssl pkcs12 -export -clcerts -inkey server.key -in server.pem -out server.p12

openssl genrsa -out private.key 2048
openssl rsa -in private.key -outform PEM -pubout -out public.key