#!/bin/sh

cd "$(dirname "$0")"

#=============
#Copy Files
#=============
rm -rf data
cp -rf Web data
rm -rf data/img

purgecss --css data/bootstrap.css --content data/*.html --whitelist bg-success,bg-danger,bg-warning --output data/css/bootstrap.css
purgecss --css data/bootstrap.slate.css --content data/*.html --whitelist bg-success,bg-danger,bg-warning  --output data/css/bootstrap.slate.css
purgecss --css data/roundslider.css --content data/*.html --whitelist --output data/css/roundslider.css
purgecss --css data/rangeslider.css --content data/*.html --whitelist --output data/css/rangeslider.css
purgecss --css data/igrowl.css --content data/*.html --whitelist --output data/css/igrowl.css
#==============
#Download Tool
#==============
mkdir -p tools
if [ ! -f tools/mklittlefs ]; then
    curl -L -o tools/x86_64-apple-darwin14-mklittlefs-295fe9b.tar.gz -k -C - https://github.com/earlephilhower/mklittlefs/releases/download/3.0.0/x86_64-apple-darwin14-mklittlefs-295fe9b.tar.gz
    cd tools
    gunzip -c x86_64-apple-darwin14-mklittlefs-295fe9b.tar.gz | tar xopf -
    mv mklittlefs ./mklittlefs-295fe9b
    mv mklittlefs-295fe9b/mklittlefs ./
    rm -rf mklittlefs-295fe9b
    cd ../
fi

#==============
#Compress Files
#==============
for f in $(find data -type f -name '*.*' ! -name '*.key' ! -name '*.cer'); do
    gzip "$f"
    mv "$f.gz" "$f"
done

mkdir -p build
./tools/mklittlefs -c ./data/ -b 8192 -p 256 -s 680000 ./build/flash-littlefs.bin
