#!/bin/sh

cd "$(dirname "$0")"

#Copy Web Files
rm -rf data
cp -rf Web data
rm -rf data/img
rm -rf data/nvram.json
rm -rf data/svg/index.html
mkdir data/img
cp -rf Web/img/cert.svg data/img
purgecss --css data/bootstrap.css --content data/*.html --whitelist bg-success,bg-danger,bg-warning --output data/css/bootstrap.css
purgecss --css data/bootstrap.slate.css --content data/*.html --whitelist bg-success,bg-danger,bg-warning  --output data/css/bootstrap.slate.css
purgecss --css data/roundslider.css --content data/*.html --whitelist --output data/css/roundslider.css
purgecss --css data/rangeslider.css --content data/*.html --whitelist --output data/css/rangeslider.css
purgecss --css data/igrowl.css --content data/*.html --whitelist --output data/css/igrowl.css

#Compress Web Files
for f in $(find data -type f -name '*.*' ! -name '*.key' ! -name '*.cer'); do
    gzip "$f"
    mv "$f.gz" "$f"
done

for dir in $(find ~/Library/Arduino15/packages/esp8266/hardware/esp8266 -depth 1 -type d); do
    esp8266="$(basename $dir)"
    break
done

for dir in $(find ~/Library/Arduino15/packages/esp8266/tools/mklittlefs/ -depth 1 -type d); do
    gcc="$(basename $dir)"
    break
done

#Build LittleFS
mkdir -p build

#Sign LittleFS
#_signed_size:      2072576 - 8192 = 2064384
#_signature:        256
#_signature_length: 4
~/Library/Arduino15/packages/esp8266/tools/mklittlefs/$gcc/mklittlefs -c ./data/ -b 8192 -p 256 -d 5 -s 2064384 ./build/flash-littlefs.bin
~/Library/Arduino15/packages/esp8266/hardware/esp8266/$esp8266/tools/signing.py --mode sign --privatekey ./private.key --bin ./build/flash-littlefs.bin --out ./build/flash-littlefs.bin.signed

#_start:            0x00200000 (2097152)
#_size:             0x001FA000 (2072576)
~/Library/Arduino15/packages/esp8266/tools/mklittlefs/$gcc/mklittlefs -c ./data/ -b 8192 -p 256 -d 5 -s 2072576 ./build/flash-littlefs.bin

#Compress LittleFS
#gzip -9 ./build/flash-littlefs.bin
#mv ./build/flash-littlefs.bin.gz ./build/flash-littlefs.bin
